[project]
authors = ["Ratul Buragohain <ratul75@hotmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "tenmo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
mojo = ">=25.6.0.dev2025082305,<26"
python = "==3.12"

[pypi-dependencies]
mnist-datasets = ">=0.14, <0.15"
