[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "tenmo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.25.7"
[pypi-dependencies]
mnist-datasets = ">=0.14, <0.15"
