[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "tenmo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
[pypi-dependencies]
mnist-datasets = ">=0.14, <0.15"
pure-cifar-10=">=0.1.1"

[dependencies]
python = ">=3.14.2,<3.15"
mojo = "==0.25.7"
